### ISSUE TITLE
PyCrypto/Python3.10 breaking change leads to error

### ISSUE THREAD

**Issue by Notselwyn** [t0thkr1s/gpp-decrypt#3]
```
[~/Documents/ctf/htb/active]$ gpp-decrypt -f Groups.xml

                               __                                __ 
  ___ _   ___    ___  ____ ___/ / ___  ____  ____  __ __   ___  / /_
 / _ `/  / _ \  / _ \/___// _  / / -_)/ __/ / __/ / // /  / _ \/ __/
 \_, /  / .__/ / .__/     \_,_/  \__/ \__/ /_/    \_, /  / .__/\__/ 
/___/  /_/    /_/                                /___/  /_/         

[ * ] Username: active.htb\SVC_TGS
Traceback (most recent call last):
  File "/usr/local/bin/gpp-decrypt", line 69, in <module>
    main()
  File "/usr/local/bin/gpp-decrypt", line 60, in main
    print(success + 'Password: ' + decrypt(cpass))
  File "/usr/local/bin/gpp-decrypt", line 29, in decrypt
    aes = AES.new(key, AES.MODE_CBC, iv)
  File "/home/lau/.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/lau/.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/lau/.local/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

Versions:
- Python 3.10.4
- pycrypto 2.6.1
- gpp-decrypt *most recent*

**Comment by Notselwyn** [comment]
Nevermind, seems like a pycrpto issue

**Comment by Diabl0269** [comment]
@Notselwyn I am facing the same issue, tried all possible versions of `pycrypto` but none work. How did you fix it?
